### PR TITLE
Bump sbt-debug-adapter

### LINKED ISSUE #2690: Test decorator and test run command in aggregate root project fail
When
* the build.sbt contains two projects
* one project ("root") contains a testing framework and tests, and `.aggregate`s the other project ("common")
* SBT is used as language server

running the `test` decorator or the `metals.test-current-file` fails with an ugly error message in the Metals output:

```
...
[Error - 11:36:15 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  no matching test group
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  no matching test group
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

2021.04.08 11:36:14 ERROR no matching test group
2021.04.08 11:36:14 ERROR (common / Test / startTestSuitesDebugSession) no matching test group
2021.04.08 11:36:14 ERROR Error -33000: 
...
```

**To Reproduce**

1. Clone this repository: https://github.com/markusa380/metals-test-error
2. Select SBT as build server (didn't test with Bloop)
3. Run the `test` decorator in `HelloSpec.scala`

**Expected behavior**

Tests work.

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.1

**Additional context**

Only tested with SBT as build server.

**Search terms**

test, decorator, command, sbt

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #2690

### CODE REVIEW

**Comment by ckipp01** [comment]
So I am still trying to figure out what's going on, but running the example linked in the issue, I'm now getting a different error that is pointing towards semantics not being produced for that file. Although I'm testing via the `test-file` functionality, not with the code lense.

```
SEVERE: Internal error: scala.meta.internal.metals.debug.SemanticDbNotFoundException$: Build misconfiguration. No semanticdb can be found for you file, please check the doctor.
java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.SemanticDbNotFoundException$: Build misconfiguration. No semanticdb can be found for you file, please check the doctor.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
        at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
        at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2112)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.thenAccept(FutureConvertersImpl.scala:37)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
        at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scala.meta.internal.metals.debug.SemanticDbNotFoundException$: Build misconfiguration. No semanticdb can be found for you file, please check the doctor.
        at scala.meta.internal.metals.debug.SemanticDbNotFoundException$.<clinit>(DebugProvider.scala)
        at scala.meta.internal.metals.debug.DebugProvider.$anonfun$debugDiscovery$3(DebugProvider.scala:286)
        at scala.Option.fold(Option.scala:251)
        at scala.meta.internal.metals.debug.DebugProvider.debugDiscovery(DebugProvider.scala:287)
        at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1629)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
        ... 10 more
```

**Comment by tgodzik** [comment]
> So I am still trying to figure out what's going on, but running the example linked in the issue, I'm now getting a different error that is pointing towards semantics not being produced for that file. Although I'm testing via the `test-file` functionality, not with the code lens.
> 
> ```
> SEVERE: Internal error: scala.meta.internal.metals.debug.SemanticDbNotFoundException$: Build misconfiguration. No semanticdb can be found for you file, please check the doctor.
> java.util.concurrent.CompletionException: scala.meta.internal.metals.debug.SemanticDbNotFoundException$: Build misconfiguration. No semanticdb can be found for you file, please check the doctor.
>         at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
>         at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)
>         at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
>         at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2112)
>         at scala.concurrent.java8.FuturesConvertersImpl$CF.thenAccept(FutureConvertersImpl.scala:37)
>         at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
>         at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
>         at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
>         at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
>         at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
>         at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: scala.meta.internal.metals.debug.SemanticDbNotFoundException$: Build misconfiguration. No semanticdb can be found for you file, please check the doctor.
>         at scala.meta.internal.metals.debug.SemanticDbNotFoundException$.<clinit>(DebugProvider.scala)
>         at scala.meta.internal.metals.debug.DebugProvider.$anonfun$debugDiscovery$3(DebugProvider.scala:286)
>         at scala.Option.fold(Option.scala:251)
>         at scala.meta.internal.metals.debug.DebugProvider.debugDiscovery(DebugProvider.scala:287)
>         at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1629)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
>         at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
>         at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
>         ... 10 more
> ```

Yeah, it's the same as me. Looks like we have wrong target root. It's using the one for main not tests.

Also, Debug tests are failing even more... What is even going on, it seems like everything is timing out :(

**Comment by tgodzik** [comment]
@olafurpg @gabro any idea if we can get better stack traces. The only thing showing up is:

==> X tests.debug.StackFrameDapSuite.foreach  14.226s java.net.SocketTimeoutException: connect timed out

But not where it's originating.

**Comment by tgodzik** [comment]
Might have been my bad: https://github.com/scalameta/metals/pull/2696

**Comment by ckipp01** [comment]
Heads up, don't merge this yet, there is some issues with CI going on and unit tests didn't run.

**Review by ckipp01 — APPROVED** [review]
So both failures are ones that are currently flaky, so I'm fine with this 👍🏼

**Review by tgodzik — APPROVED** [review]
LGTM! The failures look like they fail on some particular ubuntu runner nodes, so maybe it's some kind of a host issue ? When debug test fails, all of them fail in the given suite.

**Pull request merged**
