### PR TITLE
Support remote debugging

### LINKED ISSUE #2115: Support for remote debug
**Is your feature request related to a problem? Please describe.**

Metals currently supports debugging when metals are in charge of running jvm (tests and mains) which is awesome got tests or small application. In many cases one need to debug application that are started by other things (e.g. jvm for Metals server itself are started from within vs code) and fro such case jvm has `agentlib:` parameter (e.g. `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005`) that allows to connect to from an outside application (or with listen mode jvm would try to connect to provided address on startup).

Intellij and other IDE supports this and for now whenever I need to use it I am forced to switch back to Intellij.

**Describe the solution you'd like**

This is well establish feature from technical point of view so I don't think there is much to describe. 
I would love to see both modes (Attach and Listen) supported but having any of those will be a huge step forward.

In terms of configuration, user should be able to specify mode, port and where to  get classpath from in some shape or form. I do not have any preferences there. 

**Describe alternatives you've considered**

As mentioned this is well establish feature in other IDEs and I don't see (but I may be wrong) need to search for alternative.

**Additional context**

Configuration window from Intellij looks like this:

Screenshot from 2020-03-09 13-52-35

**Search terms**:
Remote, Debug, JDP, JDWP, Intellij

### PR DESCRIPTION
**Pull request by pvid**
Closes #2115

TODOs:
- [x] Bump bloop version after https://github.com/scalacenter/bloop/pull/1378 is merged and released
- [x] Send a PR for [scalameta/metals-vscode](https://github.com/scalameta/metals-vscode): https://github.com/scalameta/metals-vscode/pull/419

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM! Thanks for the contribution! Let's wait for the PR in Bloop to get merged.

**Comment by tgodzik** [comment]
Just merged https://github.com/scalacenter/bloop/pull/1378.  We should be good to merge after latest Bloop snapshot is released.

**Comment by pvid** [comment]
> Just merged [scalacenter/bloop#1378](https://github.com/scalacenter/bloop/pull/1378). We should be good to merge after latest Bloop snapshot is released.

seems that the [release CI](https://github.com/scalacenter/bloop/runs/1286235072?check_suite_focus=true) for bloop failed. The same error occured for the next merged PR

**Comment by tgodzik** [comment]
> > Just merged [scalacenter/bloop#1378](https://github.com/scalacenter/bloop/pull/1378). We should be good to merge after latest Bloop snapshot is released.
> 
> seems that the [release CI](https://github.com/scalacenter/bloop/runs/1286235072?check_suite_focus=true) for bloop failed. The same error occured for the next merged PR

I was trying to rerun those, but having no luck :/ Will need to take a closer look at it next week.

**Comment by tgodzik** [comment]
@pvid I haven't been able to rerun the SNAPSHOT version. I will push for 1.4.5 version and try to release it.

**Comment by tgodzik** [comment]
@pvid you should be able to use `1.4.4-25-7e876299`, but we are still planning 1.4.5 in the nearest future.

**Comment by pvid** [comment]
> @pvid you should be able to use `1.4.4-25-7e876299`, but we are still planning 1.4.5 in the nearest future.

Thanks! I'll update the PR this evening

**Comment by pvid** [comment]
@tgodzik, I upgraded bloop version and rebased onto `main`. Just to be sure, I tested the changes wit a local snapshot. It should be good to go.

**Comment by tgodzik** [comment]
Just tested it out and it works perfect! Thanks for the awesome job!

**Pull request merged**
