### PR TITLE
fix: [Scala 3] Show exact literal type

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/metals/issues/3566

### CODE REVIEW

**Review by dos65 — COMMENTED** [review]
Could you also add a test on union of constant types like it was reported in discord?
```scala
val x: 1 | 2 = ???
```

**Comment by dos65** [comment]
@tgodzik 

> Getting (1: Int | 2: Int) which is the default way, but I wonder if we shouldn't maybe keep it like that?

Looks good.
I'm thinking that maybe we should render `val x: 1` in the same way as `1: Int` .

**Comment by tgodzik** [comment]
> @tgodzik
> 
> > Getting (1: Int | 2: Int) which is the default way, but I wonder if we shouldn't maybe keep it like that?
> 
> Looks good. I'm thinking that maybe we should render `val x: 1` in the same way as `1: Int` .

That's actually easier :D I tried to work around it to be the same as Scala 2, but maybe it's not needed.

**Review by dos65 — APPROVED** [review]
:+1:

**Pull request merged**
