### PR TITLE
Add support for Scala 3.0.0-RC2

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
This looks great @tgodzik. LGTM 🚀

**Comment by tgodzik** [comment]
It turns out I can work around the description issue, so that we still get sensible completions. The issue was that overloaded symbols are all returned in a single completion, which doesn't really make sense from the Metals perspective. We need to somehow indicate the different signatures that are possible.

**Comment by tgodzik** [comment]
@tanishiking this might cause some conflict with your PR, I will take at look later on.

**Comment by tanishiking** [comment]
@tgodzik Thank you for letting me know, I'll also try to rebase  https://github.com/scalameta/metals/pull/2637 onto `main` later :)

**Pull request merged**
