### PR TITLE
Ignore flaky BspSwitchSuite and reenable FoldingRangeSuite on Windows.

### PR DESCRIPTION
**Pull request by tgodzik**
BspSwitchSuite is consistently failing on CI for Windows, but FoldingRangeSuite might be reenabled after recent fixes to the reliability of the directory watcher within tests.

### CODE REVIEW

**Comment by tgodzik** [comment]
Now they're going OOM :/

**Comment by gabro** [comment]
Could it be the -Xmx4G option which is a bit much?

**Comment by olafurpg** [comment]
Yes, I think the `-Xmx4g` option may be too much, iirc the GitHub Actions machines only have 2gb

**Comment by tgodzik** [comment]
> Yes, I think the `-Xmx4g` option may be too much, iirc the GitHub Actions machines only have 2gb

Hmm... according to https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners they have 7gb. But it might be Bloop server taking up some of it.

**Comment by gabro** [comment]
✅ all green!

**Pull request merged**
