### PR TITLE
Basic dotty support in Metals

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Comment by eaplatanios** [comment]
Is this PR being actively worked on? If so, how far is it from being usable?

**Comment by tgodzik** [comment]
> Is this PR being actively worked on? If so, how far is it from being usable?

I plan to get back to it in January, it will only support bare bones presentation compiler at first, but we will follow up with more work to make it on the level of current Scala support in Metals.

**Comment by eaplatanios** [comment]
Thanks that's great to hear! Looking forward to it! And happy new year! :)

**Comment by tgodzik** [comment]
Closing this PR, since I am reworking the dotty integration right now.

**Comment by unoexperto** [comment]
@tgodzik Is there follow up issue which records your progress?

**Comment by tgodzik** [comment]
> @tgodzik Is there follow up issue which records your progress?

Just created- https://github.com/scalameta/metals/issues/1367

I will try to fill it in later.

**Pull request closed without merging**
