### PR TITLE
Organize imports with Scalafix

### PR DESCRIPTION
**Pull request by olafurpg**
This PR replaces the `RemoveUnused` Scalafix rule with a new `OrganizeImports` rule that was created by @liancheng. Massive thanks to @liancheng! I have wanted this for a long time 😄 

Marked as a draft since `OrganizeImports` still doesn't remove unused imports but there is a draft PR that implements this functionality https://github.com/liancheng/scalafix-organize-imports/pull/9

Are everyone OK with enabling this rule once it can remove unused imports?

### CODE REVIEW

**Comment by tgodzik** [comment]
> This PR replaces the `RemoveUnused` Scalafix rule with a new `OrganizeImports` rule that was created by @liancheng. Massive thanks to @liancheng! I have wanted this for a long time 
> 
> Marked as a draft since `OrganizeImports` still doesn't remove unused imports but there is a draft PR that implements this functionality [liancheng/scalafix-organize-imports#9](https://github.com/liancheng/scalafix-organize-imports/pull/9)
> 
> Are everyone OK with enabling this rule once it can remove unused imports?

Totally ok with it. I was doing it sometimes doing it by hand in places :sweat_smile:

**Comment by gabro** [comment]
One minor thing I was wondering about is whether to split into groups the project imports and the third-party ones:

```
import java

import scala

import scala.meta.metals

import whatever.else
```

this is the convention I loosely follow in other projects. Thoughts?

**Comment by olafurpg** [comment]
@gabro that sounds reasonable and I think `OrganizeImports` supports this configuration but I haven't tried it yet.

**Comment by liancheng** [comment]
@gabro, `OrganizeImports` does support grouping 3rd party imports to a separate group:

```hocon
OrganizeImports.groups = [
  "re:javax?\\."
  "scala."
  "*"
]
```

But one problem right now is that the above configuration groups `scala.meta.` and `scala.` imports into the same group. If you put `scala.meta.` in the `groups` configuration, you'll have to put it before `scala.` to make `scala.meta.` a separate group since right now the rule groups an import to the first prefix pattern that matches.

I can probably do longest prefix matching to address it, though.

**Comment by liancheng** [comment]
@olafurpg With `OrganizeImports` v0.2.1-RC1, I think the following configuration produces a reasonable result for Metals:

```hocon
OrganizeImports.groups = [
  "re:javax?\\."
  "re:scala\\.(?!meta\\.)"
  "scala.meta.internal.metals"
  "*"
]
```

It groups `scala.meta.internal.metals` into a separate group, and leaves `scala.meta` imports in the wildcard group.

Please see the discussion [here][1].

[1]: https://github.com/liancheng/scalafix-organize-imports/pull/10#issuecomment-617625047

**Comment by gabro** [comment]
@liancheng that's great, I think we should also include `scala.meta.pc` alongside `scala.meta.internal.metals` (that's the package we use for the mtags module)

@olafurpg what do you think?

**Comment by olafurpg** [comment]
@gabro I ended up with this
```
OrganizeImports.groups = [
  "re:javax?\\."
  "scala."
  "scala.meta."
  "*"
]
```
I don't think it's necessary to distinguish `scala.meta.internal.metals` from `scala.meta.Tree`

**Comment by gabro** [comment]
Fair enough!

**Comment by olafurpg** [comment]
Merging this PR will introduce a lot of rebase git conflict. Does it make sense to try and merge some other large PRs first? For example https://github.com/scalameta/metals/pull/1538 It's easy to update this PR afterwards

**Comment by tgodzik** [comment]
> Merging this PR will introduce a lot of rebase git conflict. Does it make sense to try and merge some other large PRs first? For example #1538 It's easy to update this PR afterwards

I agree, we can fist merge the Ammonite PR, I will take care of merging this later.

**Comment by olafurpg** [comment]
Closing this PR until we're ready to merge.

**Pull request closed without merging**
