### PR TITLE
chore: Update scalafmt bootstrap

### PR DESCRIPTION
**Pull request by tgodzik**
It seems we are seeing some weird issues when pushing with an older boostrap version

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]

**Comment by ckipp01** [comment]
Actually locally this is failing for me now

```
~/Documents/scala-workspace/org-scalameta/metals main ⇡
❯ ./bin/scalafmt
Invalid version: 3.7.10: /Users/ckipp/Documents/scala-workspace/org-scalameta/metals/.scalafmt.conf
```

**Comment by tgodzik** [comment]
> Actually locally this is failing for me now
> 
> ```
> ~/Documents/scala-workspace/org-scalameta/metals main ⇡
> ❯ ./bin/scalafmt
> Invalid version: 3.7.10: /Users/ckipp/Documents/scala-workspace/org-scalameta/metals/.scalafmt.conf
> ```

Do you mean the updated version? Or the previous one?

**Comment by ckipp01** [comment]
> Do you mean the updated version? Or the previous one?

AH sorry I was on the wrong branch. Correct, this is what happens on main for me.

**Review by ckipp01 — APPROVED** [review]
LGTM!

**Pull request merged**
