### PR TITLE
Fix go to in external classes in jars with special chars

### LINKED ISSUE #4357: Cannot go to implementations of classes in external packages
**Describe the bug**

In a file of my project, I import a class from an external package by

```scala
import com.amazonaws.services.s3.AmazonS3Client
```

The package is hosted in a custom host and I need to connect to a VPN to download it. I can go to the implementations of `AmazonS3Client`, which looks like

```java
public class AmazonS3Client extends AmazonWebServiceClient implements AmazonS3 {
...
```

Then I want to go to the implementations of `AmazonS3` but it shows errors

```
[Error - 6:56:31 PM] Request textDocument/codeLens failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.FileSystemNotFoundException: /Users/me/Library/Caches/Coursier/v1/https/maven.localproxy.net:42042/repo/com/amazonaws/aws-java-sdk-s3/1.9.6/aws-java-sdk-s3-1.9.6-sources.jar
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.FileSystemNotFoundException: /Users/me/Library/Caches/Coursier/v1/https/maven.localproxy.net:42042/repo/com/amazonaws/aws-java-sdk-s3/1.9.6/aws-java-sdk-s3-1.9.6-sources.jar
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:104)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionURIMtags.toAbsolutePath(MtagsEnrichments.scala:110)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:137)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:135)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:623)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:620)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$2(MetalsLanguageServer.scala:1689)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$codeLens$1(MetalsLanguageServer.scala:1688)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:26)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	... 3 more
```

In my local, the path of the file is

```
/Users/me/Library/Caches/Coursier/v1/https/maven.localproxy.net%3A42042/repo/com/amazonaws/aws-java-sdk-s3/1.9.6/aws-java-sdk-s3-1.9.6-sources.jar
```

**Expected behavior**

I should be able to go to the implementations of `AmazonS3`.

**Installation:**

- Operating system: macOS
- VSCode version: 1.71.0
- VSCode extension version: v1.19.9
- Metals version: 0.11.8+79-e6494d3f-SNAPSHOT

### PR DESCRIPTION
**Pull request by narma**
Fixes #4357
Related changes #3632

### CODE REVIEW

**Comment by narma** [comment]
Also related to https://github.com/coursier/coursier/issues/2186

**Comment by narma** [comment]
Have tested with my case described in #4498 - works perfectly.

**Comment by narma** [comment]
Just got following exception
```
[Error - 8:35:11 PM] Request textDocument/definition failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.NoSuchFileException: /Users/alzo/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_3/2.0.2%252B92-739628d2-SNAPSHOT/zio_3-2.0.2%252B92-739628d2-SNAPSHOT-sources.jar
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /Users/alzo/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_3/2.0.2%252B92-739628d2-SNAPSHOT/zio_3-2.0.2%252B92-739628d2-SNAPSHOT-sources.jar
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:166)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionURIMtags.toAbsolutePath(MtagsEnrichments.scala:112)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:139)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:609)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:606)
	at scala.meta.internal.metals.Compilers.$anonfun$definition$3(Compilers.scala:503)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionJavaList.map(MetalsEnrichments.scala:227)
	at scala.meta.internal.metals.Compilers.$anonfun$definition$2(Compilers.scala:502)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	... 3 more
```
looks like `%` was escaped additionally to `%2B`

**Comment by tgodzik** [comment]
Thanks for the contribution! Looks like this works!

> Just got following exception

Is that with your changes? I wasn't able to reproduce the bug again with your changes.

**Comment by narma** [comment]
> Looks like this works!
For me too!

> Is that with your changes? I wasn't able to reproduce the bug again with your changes.

Yup, it happens not immediately, but after some time of intensive coding. And looks like it happens via another path or another circumstances. I just feel how complicated whole system with FS/ZipFS for now. So far, didn't investigate to this yet. Will have some time to dig into it a bit later.

For now, I make this PR is ready in case it's make sense to separate this work.

**Review by tgodzik — APPROVED** [review]
LGTM! Thanks for working on this! I tried to approach this previously but failed misarably.

**Pull request merged**
