### PR TITLE
Bump scalafmt up to 2.7.4

### PR DESCRIPTION
**Pull request by ckipp01**
Figured this might be a good time to do this seeing that we don't have any large prs open at the moment.

### CODE REVIEW

**Comment by kpbochenek** [comment]
Now I understand frustration on scalafmt gitter about defaults changing left and right and constant need to heavily reformat code ;(

(but also a huge fan of syntax `xx.map { case yy => }` instead of putting case into separate line)

**Review by kpbochenek — CHANGES_REQUESTED** [review]
Seems to be failing on all setups: `tests.DefinitionSuite`

**Comment by ckipp01** [comment]
> Now I understand frustration on scalafmt gitter about defaults changing left and right and constant need to heavily reformat code ;(

Yea, agreed. I do wish these diffs could be smaller.

> (but also a huge fan of syntax xx.map { case yy => } instead of putting case into separate line)

Agreed again. I do like this change.

> Seems to be failing on all setups: tests.DefinitionSuite

Ach, I always forget to run `save-expect`. Let me fix this.

**Review by kpbochenek — APPROVED** [review]
LGTM :+1:

**Pull request merged**
