### PR TITLE
Remove tools.jar mention and update coursier resolver

### PR DESCRIPTION
**Pull request by laughedelic**
A small change:
* we don't need tools.jar, it was used for the Ensime debugger
* changed resolver (doesn't matter for the locally published artifacts, but allows you to test some versions published to Bintray)

### CODE REVIEW

**Comment by laughedelic** [comment]
@gabro I thought about it, but what about JVM options? I searched a bit and didn't find a way to pass them with `coursier launch`. It's possible through `coursier bootstrap` though: https://github.com/coursier/coursier/issues/615.

**Comment by laughedelic** [comment]
Oh! Now I got what you mean 😅 Just to remove `getJavaHome`, but still use `java` from the `PATH` to launch 👌

**Comment by laughedelic** [comment]
@gabro please, try it out before merging. I tried and it seems to work, but I don't know if I have to clean some VSCode extensions cache or something.

**Comment by gabro** [comment]
@laughedelic tested on my machine, it works fine 👍

**Pull request merged**
