### PR TITLE
fix: prevent npe in filewatcher

### LINKED ISSUE #3961: Syntactically incorrect using directive breaks build
### Describe the bug

1. Create a file:
UnclosedLiteral.scala:
```scala
//> using scala 3.1.2

def foo[T] = ???
def bar = foo[""]
```

2. Run
```scala-cli setup-ide UnclosedLiteral.scala```

3. Open the project in VSCode

4. Metals' output:
```
2022.05.27 14:04:38 WARN  File watching failed, indexes will not be updated.
java.lang.NullPointerException
	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.isSemanticdb(CommonMtagsEnrichments.scala:520)
	at scala.meta.internal.metals.MetalsLanguageServer.fileWatchFilter(MetalsLanguageServer.scala:1356)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$2(MetalsLanguageServer.scala:208)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$2$adapted(MetalsLanguageServer.scala:208)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$startWatch$2(FileWatcher.scala:144)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$startWatch$2$adapted(FileWatcher.scala:144)
	at scala.meta.internal.metals.watcher.FileWatcher$.hashFile(FileWatcher.scala:199)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$initFileTreeRepository$1(FileWatcher.scala:171)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$initFileTreeRepository$1$adapted(FileWatcher.scala:168)
	at com.swoval.files.Entries.get(Entries.java:27)
	at com.swoval.files.CachedDirectoryImpl.<init>(CachedDirectoryImpl.java:64)
	at com.swoval.files.CachedDirectoryImpl.<init>(CachedDirectoryImpl.java:76)
	at com.swoval.files.FileCacheDirectoryTree.newCachedDirectory(FileCacheDirectoryTree.java:629)
	at com.swoval.files.FileCacheDirectoryTree.register(FileCacheDirectoryTree.java:449)
	at com.swoval.files.FileCachePathWatcher.register(FileCachePathWatcher.java:24)
	at com.swoval.files.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.java:101)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$startWatch$3(FileWatcher.scala:149)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.watcher.FileWatcher$.scala$meta$internal$metals$watcher$FileWatcher$$startWatch(FileWatcher.scala:147)
	at scala.meta.internal.metals.watcher.FileWatcher.restart(FileWatcher.scala:60)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$7(Indexer.scala:228)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:227)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Expected behavior

Metals should not crash and show an error about the incorrect using directive instead

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.5

### Extra context or search terms

scala-cli v0.1.6

### PR DESCRIPTION
**Pull request by dos65**
Fixes #3961

### CODE REVIEW

**Review by kpodsiad — COMMENTED** [review]
Is this ok that event refers to path which is null?

**Review by tanishiking — APPROVED** [review]
I'm not sure how the path become null (maybe swoval's bug?), but as a workaround, LGTM

**Review by tgodzik — APPROVED** [review]
LGTM not sure if we should report it upstream in swoval?

**Comment by kpodsiad** [comment]
It's not a swoval bug ;)

**Pull request merged**
