### PR TITLE
Use `appendWithSession` instead of `append`

### PR DESCRIPTION
**Pull request by Duhemm**
`append` (deprecated, equivalent to `appendWithoutSession`) will add
settings and discard other settings that may have been added in the
sessions since the build was loaded.

This commit replaces `append` with `appendWithSession`, so that these
settings are not lost.

Discovered in scalacenter/load-plugin#1

Thanks @jvican for making me aware of the existence of `appendWithSession` 😄

### CODE REVIEW

**Comment by Duhemm** [comment]
Oops, this won't work for sbt 0.13.

**Comment by laughedelic** [comment]
Yes, I tried that, but it doesn't work with sbt 0.13

**Comment by gabro** [comment]
Can we dynamically fallback to `append` in sbt 0.13? `append` also generates a warning during compilation of `MetalsPlugin.scala`.

**Comment by Duhemm** [comment]
I'm fixing the PR as we speak.

**Comment by Duhemm** [comment]
I added the `Compat` object, looks like the build is passing now 🎉 

I had to inline the definition of `appendWithSession` since it is only available in sbt 1.1. I could as well do it for sbt 0.13 if you prefer.

**Comment by gabro** [comment]
Since you had to inline `appendWithSession`, isn't it possible to just have a single implementation and avoid the `scala-sbt-<version>` fork?

**Comment by laughedelic** [comment]
It gets a bit too complicated for a deprecation warning fix. Also there was an intention to keep the plugin in a single file: https://github.com/scalameta/metals/pull/230#issuecomment-378522987.

So if the code in `scala-sbt-1.0/sbt/Compat.scala` works for all versions of sbt (0.13, 1.0, 1.1) then let's keep only it and move it to `MetalsPlugin.scala`.

**Comment by gabro** [comment]
> So if the code in scala-sbt-1.0/sbt/Compat.scala works for all versions of sbt (0.13, 1.0, 1.1) then let's keep only it and move it to MetalsPlugin.scala.

Yep, that's what I was (poorly) trying express in my comment above.

**Comment by Duhemm** [comment]
I've made it single-file, but it's a bit ugly...

**Comment by laughedelic** [comment]
I agree, I would also prefer to split it in several files, but I think it's not a big deal so far.

**Pull request merged**
