### PR TITLE
Use Scalafmt 2.0.0 when setting the version in .scalafmt.conf

### LINKED ISSUE #801: Update default Scalafmt version to 2.0.0
Scalafmt 2.0.0 can format 2.13-specific features, so we should default to it when adding the version to `.scalafmt.conf` files (or creating them from scratch).

It should be a matter of changing https://github.com/scalameta/metals/blob/4851df4499d864cdf016d19747072e4139844dae/build.sbt#L148 and adding a test.

### PR DESCRIPTION
**Pull request by gabro**
Closes #801

### CODE REVIEW

**Comment by gabro** [comment]
The Azure failure looks legit, but I won't be at a computer until next weekend.
It anyone wants to pick this up feel free, otherwise I'll get back to it when I'm back!

**Comment by olafurpg** [comment]
The test failure is legit and it's caused by a recent regression in scalafmt-dynamic https://github.com/scalameta/scalafmt/issues/1442 We can work around it for now by using an older version of scalafmt-dynamic but still recommend 2.0.0

**Comment by gabro** [comment]
@tgodzik the failure in https://dev.azure.com/olafurpg/Metals/_build/results?buildId=649 looks spurious, are you able to restart it?

**Comment by tgodzik** [comment]
I think we can merge, but we need to figure out how to fix the Hover tests - they seem to failing pretty consistently.

**Pull request merged**
