### PR TITLE
bugfix: match completions for type aliases scala 3

### PR DESCRIPTION
**Pull request by kasiaMarek**
resolves: https://github.com/scalameta/metals/issues/5712

### CODE REVIEW

**Review by jkciesluk — CHANGES_REQUESTED** [review]
For `case` completions I think you need to change it also here https://github.com/scalameta/metals/pull/5714/files#diff-8cca6f591058d93dae851ed5830ec69c9172cb020410921fe8dddff10d3d8e9eR153

**Review by kpodsiad — APPROVED** [review]
Thanks for doing this!

**Review by filipwiech — APPROVED** [review]
Thank you for adding Scala 2 tests. :+1:

**Review by jkciesluk — APPROVED** [review]
LGTM

**Pull request merged**
