### PR TITLE
Remove some redundant collection conversions

### PR DESCRIPTION
**Pull request by Duhemm**

### CODE REVIEW

**Comment by ckipp01** [comment]
Looks like a consistent failure in the `TreeViewLspSuite` with a very unhelpful diff 😆 

```
[error] ==> X tests.TreeViewLspSuite.projects  3.961s munit.ComparisonFailException: /home/runner/work/metals/metals/tests/unit/src/test/scala/tests/TreeViewLspSuite.scala:110
[error] 109:      )
[error] 110:      _ = server.assertTreeViewChildren(
[error] 111:        s"projects:${server.buildTarget("a")}!/_empty_/",
[error] diff assertion failed
[error] => Obtained
[error] "Zero class -"
[error] => Diff (- obtained, + expected)
[error] -Zero class -
[error] +Zero class +
[error]     at munit.Assertions.failComparison(Assertions.scala:297)
[error]     at munit.Assertions.failComparison$(Assertions.scala:287)
[error]     at tests.Assertions$.failComparison(Assertions.scala:81)
[error]     at munit.Assertions$$anon$1.handle(Assertions.scala:31)
[error]     at munit.internal.difflib.Diffs$.assertNoDiff(Diffs.scala:51)
[error]     at munit.Assertions.$anonfun$assertNoDiff$1(Assertions.scala:67)
[error]     at munit.internal.console.StackTraces$.dropInside(StackTraces.scala:10)
[error]     at munit.Assertions.assertNoDiff(Assertions.scala:67)
[error]     at munit.Assertions.assertNoDiff$(Assertions.scala:61)
[error]     at tests.Assertions$.assertNoDiff(Assertions.scala:81)
[error]     at tests.TestingServer.assertTreeViewChildren(TestingServer.scala:1591)
[error]     at tests.TreeViewLspSuite.$anonfun$new$6(TreeViewLspSuite.scala:110)
[error]     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]     at java.lang.Thread.run(Thread.java:833)```

**Comment by tgodzik** [comment]
> Looks like a consistent failure in the `TreeViewLspSuite` with a very unhelpful diff laughing
> 
> ```
> [error] ==> X tests.TreeViewLspSuite.projects  3.961s munit.ComparisonFailException: /home/runner/work/metals/metals/tests/unit/src/test/scala/tests/TreeViewLspSuite.scala:110
> [error] 109:      )
> [error] 110:      _ = server.assertTreeViewChildren(
> [error] 111:        s"projects:${server.buildTarget("a")}!/_empty_/",
> [error] diff assertion failed
> [error] => Obtained
> [error] "Zero class -"
> [error] => Diff (- obtained, + expected)
> [error] -Zero class -
> [error] +Zero class +
> [error]     at munit.Assertions.failComparison(Assertions.scala:297)
> [error]     at munit.Assertions.failComparison$(Assertions.scala:287)
> [error]     at tests.Assertions$.failComparison(Assertions.scala:81)
> [error]     at munit.Assertions$$anon$1.handle(Assertions.scala:31)
> [error]     at munit.internal.difflib.Diffs$.assertNoDiff(Diffs.scala:51)
> [error]     at munit.Assertions.$anonfun$assertNoDiff$1(Assertions.scala:67)
> [error]     at munit.internal.console.StackTraces$.dropInside(StackTraces.scala:10)
> [error]     at munit.Assertions.assertNoDiff(Assertions.scala:67)
> [error]     at munit.Assertions.assertNoDiff$(Assertions.scala:61)
> [error]     at tests.Assertions$.assertNoDiff(Assertions.scala:81)
> [error]     at tests.TestingServer.assertTreeViewChildren(TestingServer.scala:1591)
> [error]     at tests.TreeViewLspSuite.$anonfun$new$6(TreeViewLspSuite.scala:110)
> [error]     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
> [error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [error]     at java.lang.Thread.run(Thread.java:833)```
> ```

Actually I think it's supposed to be `Zero class +` instead of `Zero class -` as in:

```
val collapse =
          if (node.isExpanded) " +"
          else if (node.isCollapsed) " -"
          else ""
```

**Comment by ckipp01** [comment]
> Actually I think it's supposed to be Zero class + instead of Zero class - as in:

ahhhh I thought the `-` and `+` were part of the diff syntax haha

**Review by ckipp01 — APPROVED** [review]
Thanks a lot for this @Duhemm!

LGTM!

**Pull request merged**
