### PR TITLE
Look into ammonite flakiness in tests to see if we can remove it

### PR DESCRIPTION
**Pull request by ckipp01**
A lot has changed since #1801 was created. I'm going to run the tests on this a bit and see if this may have solved itself.

### CODE REVIEW

**Comment by ckipp01** [comment]
One full run with all ✅ . I'll do another just to make sure.

**Comment by ckipp01** [comment]
Multiple runs with no issues. I think we are ok to remove the `flaky` tag here.

**Review by kpbochenek — APPROVED** [review]
Yup looking good :+1:

**Comment by ckipp01** [comment]
There is one test failure, but it's not related to Amm so I'm going to go ahead and merge this.

**Pull request merged**
