### PR TITLE
Update emacs support table

### PR DESCRIPTION
**Pull request by kurnevsky**
- worksheets with decoration protocol are fully supported
- lsp-metals supports quite a lot of metals extensions
- source file analyzer commands are supported

### CODE REVIEW

**Comment by kurnevsky** [comment]
btw, how metals is installed in vim? I wonder if I should change emacs to `single click` because it can be installed automatically if `lsp-mode` is present :)

**Comment by tgodzik** [comment]
> btw, how metals is installed in vim? I wonder if I should change emacs to `single click` because it can be installed automatically if `lsp-metals` is present :)

I think via coursier, but most likely @ckipp01 can correct me.

**Comment by kurnevsky** [comment]
Well, emacs can install metals via coursier as well :)

**Comment by tgodzik** [comment]
> Well, emacs can install metals via coursier as well :)

Hmm... actually vim might also be doing that without a need to provide a bootstraped binary. By all means if it only needs lsp-metals then I would say it's "one click" installation

**Comment by kurnevsky** [comment]
ok, changed that line. It might not always work, though, because we rely on automatically downloaded binaries. I'm not sure how it works for apple M1 (probably it emulates x86 automatically?), but for nix/guix these binaries [don't work](https://github.com/emacs-lsp/lsp-metals/issues/68). Not sure, maybe we should change it to jars...

**Comment by ckipp01** [comment]
I think via coursier, but most likely @ckipp01 can correct me.

Yup, under the hood it just uses coursier to bootstrap everything.

**Pull request merged**
