### PR TITLE
improvement: if no binary version in jar path try using build target info

### PR DESCRIPTION
**Pull request by kasiaMarek**
For jars if no scala version included in the path, fallback to using scala version from build target before defaulting to "2.13".

resolves: https://github.com/scalameta/metals/issues/6693

### CODE REVIEW

**Comment by tgodzik** [comment]
We could also try to check if there tasty files, but this is already a good improvement

**Comment by kasiaMarek** [comment]
> We could also try to check if there tasty files

That's a better way to do this.

**Review by tgodzik — APPROVED** [review]
Aside from the naming comment LGTM!

**Comment by tOverney** [comment]
@tgodzik @kasiaMarek what's holding up these changes?
Fixing the source jar navigation in those cases would be the biggest improvement on metals for me :)

**Comment by kasiaMarek** [comment]
> what's holding up these changes?

I'm afraid, I am. I need to address Tomek's review comment and it can be merged after that.

**Pull request merged**
