### PR TITLE
chore: Change release notes to properly show in VS Code

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Comment by tgodzik** [comment]
The reason for that is here https://github.com/scalameta/metals-vscode/blob/main/packages/metals-vscode/src/releaseNotesProvider.ts#L203 :sweat: 

I will fix it on the plugin side, but for now I will merge this.

**Comment by tgodzik** [comment]
Actually, that might not have been needed :thinking: 

I can't reproduce the issue I've been having :face_exhaling:

**Comment by tgodzik** [comment]
Ach no, that's actually fixed, but we take the markdown file from code and not from the blog. Anyway, I will look into this

**Comment by tgodzik** [comment]
And it's here https://github.com/scalameta/metals-vscode/pull/1408

**Comment by kpodsiad** [comment]
I wonder who put this line there 😅

**Comment by tgodzik** [comment]
I wonder who reviewed it 🤣

**Pull request merged**
