### PR TITLE
Update organize-import rule to add Scala 2.11 support

### PR DESCRIPTION
**Pull request by gabro**
Partially addresses #2099 by adding 2.11 support for organize imports (the error reporting part is still missing)

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Cool! Thanks for working on this! LGTM

**Review by mlachkar — APPROVED** [review]
Where do you think the error should be shown?  is it in Metals logs?

**Comment by gabro** [comment]
@mlachkar I think the precise error (failed to download Scalafix, or failed to download the rules) should be logged and we should also display a "user-friendly" error in the editor, something like ("Organize imports failed due to an unexpected problem, check the logs for more information")

**Comment by tgodzik** [comment]
@gabro @mlachkar  should we add `-Ywarn-unused-import` for Scala 2.11 here https://github.com/scalameta/metals/blob/a3d0d9488bdfe3119a7ca34060e37f642cd0591b/metals/src/main/scala/scala/meta/internal/metals/ScalafixProvider.scala#L61 ?

**Comment by gabro** [comment]
I think it's already covered by the else case, isn't it?

**Comment by tgodzik** [comment]
> I think it's already covered by the else case, isn't it?

Ach nevermind, I somehow thought it's a different flag.

**Pull request merged**
