### PR TITLE
Scala 3 template was moved from lampepfl org

### PR DESCRIPTION
**Pull request by tgodzik**
Follow up from https://github.com/scalameta/metals/pull/2294

It changed again and I haven't really noticed :sweat:

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
lol teaches us to change things without actually testing that they work 😬 LGTM!

**Comment by ckipp01** [comment]
Just tested this out, and it works aok. I'm going to go ahead and merge it right away.

**Comment by kpbochenek** [comment]
@ckipp01 even if you tested that it would simply work. When you move project from one workspace to another github actually creates a symlink in previous place to link to a new one.
You can try create new project even now from `lampepfl/scala3.g8` and it will still work.

**Comment by ckipp01** [comment]
> @ckipp01 even if you tested that it would simply work. When you move project from one workspace to another github actually creates a symlink in previous place to link to a new one.
> You can try create new project even now from `lampepfl/scala3.g8` and it will still work.

ahh true, good point!

**Pull request merged**
