### PR TITLE
Cross-build sbt-metals for sbt2

### PR DESCRIPTION
**Pull request by keynmol**
I'm not 100% sure what I'm doing, but let's see...

### CODE REVIEW

**Comment by tgodzik** [comment]
Thanks! I added testing to be run for the plugin, though it seems enabling semanticdb is duplicating some options. Should we raise it?

**Comment by keynmol** [comment]
While this was surprisingly easy, there's a bunch of other plugins (for debug adapter) that need to be cross-published for the injected built to even start up.

**Comment by keynmol** [comment]
> though it seems enabling semanticdb is duplicating some options

I think so, seems like bug

**Comment by tgodzik** [comment]
> While this was surprisingly easy, there's a bunch of other plugins (for debug adapter) that need to be cross-published for the injected built to even start up.

Forgot about that, we can stop adding it for sbt 2 for now.

**Comment by tgodzik** [comment]
Raised an issue here https://github.com/sbt/sbt/issues/7956

**Comment by keynmol** [comment]
Let's definitely merge _any support_ - once merged I'll test some more.
Would be good to say that basic metals functionality works in sbt 2 :)

**Review by tgodzik — APPROVED** [review]
Let's merge this and we can fix debugging later on.

**Comment by tgodzik** [comment]
Thanks @keynmol for raising this!

**Pull request merged**
