### PR TITLE
bugfix: Don't override JAVA_HOME if it already exists

### PR DESCRIPTION
**Pull request by tgodzik**
This might cause issues with for example Bazel as it might be restarted on terminal

### CODE REVIEW

**Comment by kasiaMarek** [comment]
For other build tools like `mill` we need to override this to start it with project's java version (if specified in `metals.javaVersion`). Otherwise the setting doesn't really make much sense.

**Comment by tgodzik** [comment]
Changed it to only work for Bazel, the other option is to only warn when overriding and leave it up to the user to upgrade :thinking:

**Comment by tgodzik** [comment]
@kasiaMarek what do you think?

**Comment by kasiaMarek** [comment]
> what do you think?

Honestly, not sure. Neither of the options sound very well. I think it may be okay to ignore `javaHome` from metals settings for Bazel but maybe we should add a warning, at least to Metals doctor, if `javaHome` in metals settings is set and differs from system `JAVA_HOME`.

**Comment by tgodzik** [comment]
> > what do you think?
> 
> Honestly, not sure. Neither of the options sound very well. I think it may be okay to ignore `javaHome` from metals settings for Bazel but maybe we should add a warning, at least to Metals doctor, if `javaHome` in metals settings is set and differs from system `JAVA_HOME`.

Added a warning to the logs, that should be enough especially when debugging for a user.

**Review by kasiaMarek — APPROVED** [review]

**Pull request merged**
