### PR TITLE
Update Ammonite to support Scala 2.12.13

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/metals/issues/2392

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
~Glad to have this fixed. LGTM!~

**Review by ckipp01 — CHANGES_REQUESTED** [review]
Actually sorry looking closer I totally missed that the Ammonite LSP tests were failing. We'll need to figure out what's going on with these releases...

**Comment by tgodzik** [comment]
> Actually sorry looking closer I totally missed that the Ammonite LSP tests were failing. We'll need to figure out what's going on with these releases...

Yeah, I noticed that something seems off. I will investigate next week.

**Comment by alexarchambault** [comment]
I think the issue lies in ammonite-runner. It needs to pull amm-compiler along the other Ammonite dependencies it fetches, because of https://github.com/lihaoyi/Ammonite/pull/1144.

**Comment by tgodzik** [comment]
> I think the issue lies in ammonite-runner. It needs to pull amm-compiler along the other Ammonite dependencies it fetches, because of [com-lihaoyi/Ammonite#1144](https://github.com/com-lihaoyi/Ammonite/pull/1144).

@alexarchambault do you need any help with that?

**Comment by alexarchambault** [comment]
That should be fine, thanks! ammonite-runner `0.3.1` should be on its way to Maven Central. I didn't try, but it ought to fix the errors we're seeing here.

**Pull request closed without merging**
