### PR TITLE
Changes to sourcegraph.yml

### PR DESCRIPTION
**Pull request by ckipp01**

### CODE REVIEW

**Comment by ckipp01** [comment]
@olafurpg do you have any idea why these are constantly failing now?

```
25h25l❌ Failed to upload index file
25hunexpected status code: 404
[error] (ThisBuild / sourcegraphUpload) com.sourcegraph.sbtsourcegraph.SourcegraphPlugin$TaskException: 'src' failed with exit code '1'. To reproduce this error, run the following command:
[error] src lsif upload --github-token=*** --commit=c1e11695b679fac130d66e5ad670fac9f1a18bfd --file=/home/runner/work/metals/metals/target/sbt-sourcegraph/dump.lsif --root=
[error] Total time: 123 s (02:03), completed Sep 18, 2021 2:20:33 PM
```

**Comment by tgodzik** [comment]
I disabled the workflow manually for now, @olafurpg let us know when it's possible to use sourcegraph again.

**Comment by olafurpg** [comment]
Hey! I'm sorry for the delayed response. It's OK to disable the workflow for now. I don't know what's causing the 404s, but it could be related to the fact that they been significantly scaling up the number of indexed repos lately.

**Comment by olafurpg** [comment]
I opened a new PR using the new `lsif-java index` command instead of `sbt sourcegraphUpload` #3152 The upload job seems to be working again

**Comment by tgodzik** [comment]
With #3152 merged we can close this one. Thanks!

**Pull request closed without merging**
