### PR TITLE
Try fixing the Windows CI

### PR DESCRIPTION
**Pull request by gabro**
Let's see whether this fixes the CI on Windows.

My suspicion is that the recent rewrite of the Windows Sbt launcher (https://github.com/sbt/sbt-launcher-package/commit/b5fd78f74bf1dc38bbc4203067dabb0f54dd5ea7#diff-0e467aba72fad1d1010d8efae1c500d6) has a regression in the handling of `.jvmopts`

### CODE REVIEW

**Comment by gabro** [comment]
mm, I guess I was wrong. Windows CI is still failing even with 1.3.3

**Comment by olafurpg** [comment]
The logs make it look like the issue is not caused by sbt but by the `bash` script mode on Windows.
```
Resolution error: Error downloading ch.epfl.scala:bloopgun-core_2.12:1.3.42511815
  not found: C:\Users\runneradmin\.ivy2\local\ch.epfl.scala\bloopgun-core_2.12\1.3.42511815\ivys\ivy.xml
  not found: https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun-core_2.12/1.3.42511815/bloopgun-core_2.12-1.3.42511815.pom
```

I wonder if GitHub Actions just updated their `windows-latest` image 🤔

**Comment by gabro** [comment]
@olafurpg ah, that might actually be. On the documentation, you can see

image

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

which hints at the fact that something has changed on December 3rd (recently)

**Comment by gabro** [comment]
@olafurpg I’ve found an issue with a regex in the test script which didn’t play well with the “snapshot” version of bloop.
I’ve fixed it in the latest commit, but it seems unrelated to the JVM failure

**Comment by olafurpg** [comment]
Back to green CI 🎉

**Pull request merged**
