### PR TITLE
bugfix: CompletionPosition inferStart should not crash

### PR DESCRIPTION
**Pull request by jkciesluk**
Error 01.11 reported from Scastie using reporting mechanisms

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]

**Review by tgodzik — CHANGES_REQUESTED** [review]
Actually, it looks like some tests are failing :

**Comment by kasiaMarek** [comment]
> Actually, it looks like some tests are failing :

The failing test has nothing to do with changes in the PR (https://github.com/scalameta/metals/pull/6264).

**Comment by tgodzik** [comment]
> > Actually, it looks like some tests are failing :
> 
> The failing test has nothing to do with changes in the PR (#6264).

Are we sure about that?
```
[error] ==> X tests.feature.Worksheet3NextSuite.import-missing-symbol  8.986s munit.ComparisonFailException: /home/runner/work/metals/metals/tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala:906
[error] 905:        // Assert if indentation is correct. See `AutoImports.renderImport`
[error] 906:        _ = assertNoDiff(
[error] 907:          server.bufferContents(path),
[error] diff assertion failed
[error] => Obtained
[error]     """|//> using scala 3.4.1
[error]        |
[error]        |// Some comment
[error]        |
[error]        |// Object comment
[error]        |import scala.concurrent.Future
[error]        |object A {
[error]        |  val f = Future.successful(42)
[error]        |}
[error]        |""".stripMargin
[error] => Diff (- obtained, + expected)
[error]  // Some comment
[error] +import scala.concurrent.Future
[error]  ∙
[error]  // Object comment
[error] -import scala.concurrent.Future
[error]  object A {
[error]     at munit.Assertions.failComparison(Assertions.scala:274)
```

I tried rerunning and the test failed again.

**Comment by kasiaMarek** [comment]
> I tried rerunning and the test failed again.

Works after rebase. I don't think that just re-running will take the newest changes from `main`, it may be always using the state that was "on push".

**Review by tgodzik — APPROVED** [review]
my bad, thanks!

**Pull request merged**
