### PR TITLE
Upgrade bloop-launcher to nightly version of Bloop.

### PR DESCRIPTION
**Pull request by olafurpg**
The latest launcher has some improvements that help with the Pants
integration. We still keep the stable Bloop version for users.

### CODE REVIEW

**Comment by olafurpg** [comment]
@tgodzik what happens if we just upgrade to the latest Bloop? Will users get a prompt that they're running an old version of Bloop?

**Comment by tgodzik** [comment]
> @tgodzik what happens if we just upgrade to the latest Bloop? Will users get a prompt that they're running an old version of Bloop?

The logic for checking version only works up to a `patch` version, so it will not create a prompt for users. Everything is in `SemVer`.

**Comment by olafurpg** [comment]
Sounds good, I may remove the `bloopNightly` variable in that case and upgrade to the latest instead.

```
[error] Failed: Total 900, Failed 1, Errors 0, Passed 895, Skipped 4
[error] Failed tests:
[error] 	tests.BspSwitchLspSuite
```
I'm unable to find the failed tests from the logs 🤔

**Comment by olafurpg** [comment]
Yet another unrelated failure
```
==> X tests.sbt.SbtLspSuite.fatal-warnings  15.238s java.lang.IllegalArgumentException: requirement failed: Build server did not initialize
INFO  tests.TestingServer#initialize
INFO  logging to file /home/runner/work/metals/metals/tests/slow/target/e2e/sbt-import/sbt-script/.metals/metals.log
INFO  started: Metals version 0.8.0+140-004bb885-SNAPSHOT in workspace '/home/runner/work/metals/metals/tests/slow/target/e2e/sbt-import/sbt-script'
INFO  time: initialize in 0.7s
INFO  running '/home/runner/work/metals/metals/tests/slow/target/e2e/sbt-import/sbt-script/does-not-exist -Dbloop.export-jar-classifiers=sources bloopInstall'
INFO  build tool exit: -2147483648
Jan 30, 2020 2:30:46 PM com.zaxxer.nuprocess.linux.LinuxProcess start
INFO  time: ran 'sbt bloopInstall' in 61ms
WARNING: Failed to start process
java.io.IOException: error=2, No such file or directory
	at com.zaxxer.nuprocess.internal.LibJava10.Java_java_lang_ProcessImpl_forkAndExec(Native Method)
```
The CI gods really don't want any merged PRs today 😟

**Comment by tgodzik** [comment]
@olafurpg That failure is related - resolvers for scalacenter are not being added, so snapshots are not working.

**Comment by olafurpg** [comment]
The bloop release is published to Maven Central. The bintray:scalacenter/releases resolver is no longer used.

The following command  succeeds for me without custom resolvers
```
cs fetch ch.epfl.scala:bloop-launcher-core_2.12:1.3.4+298-2c6ff971
```

**Comment by tgodzik** [comment]
> The bloop release is published to Maven Central. The bintray:scalacenter/releases resolver is no longer used.
> 
> The following command succeeds for me without custom resolvers
> 
> ```
> cs fetch ch.epfl.scala:bloop-launcher-core_2.12:1.3.4+298-2c6ff971
> ```

Hmm... ok then I am out of ideas. Must have been a delay or some network hiccup? Though it's weird so many failed at the same time.

**Comment by tgodzik** [comment]
I double checked locally and I am also having the exact same issue:
```
[info] Updating ProjectRef(uri("file:/home/tgodzik/Documents/workspaces/dotty-example-project/project/"), "dotty-example-project-build")...
[warn] 	module not found: ch.epfl.scala#sbt-bloop;1.4.0-RC1+33-dfd03f53
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.scala/sbt-bloop/scala_2.12/sbt_1.0/1.4.0-RC1+33-dfd03f53/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/ch.epfl.scala/sbt-bloop/scala_2.12/sbt_1.0/1.4.0-RC1+33-dfd03f53/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/tgodzik/.ivy2/local/ch.epfl.scala/sbt-bloop/scala_2.12/sbt_1.0/1.4.0-RC1+33-dfd03f53/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/ch/epfl/scala/sbt-bloop_2.12_1.0/1.4.0-RC1+33-dfd03f53/sbt-bloop-1.4.0-RC1+33-dfd03f53.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/tgodzik/.sbt/preloaded/ch.epfl.scala/sbt-bloop/1.4.0-RC1+33-dfd03f53/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/tgodzik/.sbt/preloaded/ch/epfl/scala/sbt-bloop_2.12_1.0/1.4.0-RC1+33-dfd03f53/sbt-bloop-1.4.0-RC1+33-dfd03f53.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: ch.epfl.scala#sbt-bloop;1.4.0-RC1+33-dfd03f53: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by tgodzik** [comment]
I got it! We need to update sbt version in `SbtLspSuite` - it's currently 1.2.6 and it's using ivy that has some issues with the way coursier is publishing plugins currently.

**Comment by olafurpg** [comment]
I upgraded the sbt version for those tests

**Comment by olafurpg** [comment]
CI is green!

**Pull request merged**
