### PR TITLE
Revert "Update directory-watcher to 0.8.3"

### PR DESCRIPTION
**Pull request by olafurpg**
The PR #1108 introduced an uncaught regression on macOS. 

```
Exception in thread "pool-2-thread-2" java.lang.NoSuchFieldError: SIZE
	at com.zaxxer.nuprocess.osx.OsxProcess.createPosixSpawnFileActions(OsxProcess.java:191)
	at com.zaxxer.nuprocess.osx.OsxProcess.createPosixPipes(OsxProcess.java:150)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:58)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.process.SystemProcess$.run(SystemProcess.scala:27)
	at scala.meta.internal.pantsbuild.Filemap$.fromPants(Filemap.scala:40)
	at scala.meta.internal.pantsbuild.BloopPants$.$anonfun$bloopInstall$1(BloopPants.scala:133)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.meta.internal.pantsbuild.BloopPants$.interruptedTry(BloopPants.scala:109)
```

Now, we run tests on macOS to prevent further regressions.

### CODE REVIEW

**Comment by olafurpg** [comment]
I remember having manually tried upgrading directory-watcher but hitting on the same issue 😟 I'm tempted to try and use another library instead like https://github.com/lihaoyi/os-lib/

**Comment by olafurpg** [comment]
Looks like we have some work to do to fix failing tests on macOS :sob: 

```
[error] Failed tests:
[error] 	tests.ImplementationSuite
[error] 	tests.ReferenceLspSuite
[error] 	tests.RenameLspSuite
```

**Comment by tgodzik** [comment]
I checked on a Mac and it seems there is a race - the tests are are run before semanticDB files are added to Bloom filters - maybe we can register in the directory watcher to await also the semanticDB files in TestServer.

**Comment by olafurpg** [comment]
@tgodzik thank you for checking it out! That sounds plausible. I'll see we can do.

**Comment by olafurpg** [comment]
@tgodzik I can confirm that it looks indeed like a race. Adding a `Thread.sleep()` seems to make the tests pass 🤔 

The core of the problem is that the tests are relying on the file watcher notifications to trigger for the indexer to process SemanticDB files.

**Comment by olafurpg** [comment]
I believe the latest commit fixes the macOS issues in a not too hacky way. Instead of relying on file watching notifications when running tests, we now walk the META-INF/semanticdb directory after "compile finished" notifications and manually trigger file watching notifications for SemanticDB files. 

Given the issues we have experience with file watching, I am tempted to try https://github.com/lihaoyi/os-lib/#oswatchwatch to see if that implementation is more reliable than our current file watching library.

**Comment by olafurpg** [comment]
CI is green! 🎉

**Comment by tgodzik** [comment]
> CI is green!

 cool! :heart_eyes:

**Pull request merged**
