### PR TITLE
bugfix: Include method signature in the label

### PR DESCRIPTION
**Pull request by tgodzik**
Previously, we would be getting a lot of messages such as:

```
Caused by: java.lang.IllegalArgumentException: 76 is not a valid line number, allowed [0..72]
    at scala.meta.internal.inputs.InternalInput.lineToOffset(InternalInput.scala:37)
    at scala.meta.internal.inputs.InternalInput.lineToOffset$(InternalInput.scala:32)
```
which most likely are cause by the fact that input is not the same as the one used for position (most likely file changed and wasn't reparsed again)

Now, we explicitely handle any issues when the position is not available.

### CODE REVIEW

**Comment by tgodzik** [comment]
Btw. I used the new code action in a couple of places, great work @vzmerr !

**Review by tanishiking — COMMENTED** [review]
The change looks good, but the commit message and PR title don't align with the change (?)

**Review by tanishiking — APPROVED** [review]
LGTM!
So, now we can handle the exception by ourselves, do we still need to investigate the root cause of the exceptions?

**Comment by tgodzik** [comment]
> LGTM! So, now we can handle the exception by ourselves, do we still need to investigate the root cause of the exceptions?

If the position cannot be found in the document, scalameta throws an exception, so that's expected really, but we should handle it explicitely.

**Pull request merged**
