### PR TITLE
chore: change formatting of trailing commas

### PR DESCRIPTION
**Pull request by kpodsiad**
Just a proposition to reduce comma noise in PR's. (for example https://github.com/scalameta/metals/pull/4049/files)

I decided to create PR instead of creating discussion so everyone can look at changes and decide if this is cool or not. I think [multiple](https://scalameta.org/scalafmt/docs/configuration.html#trailing-commas-multiple) is the most sensible option.

### CODE REVIEW

**Comment by tgodzik** [comment]
Looks good to me, though it's terrible amount of changes. It would be good to rewrite history to remove it from git blame.

**Comment by armanbilge** [comment]
> It would be good to rewrite history to remove it from git blame.

`--ignore-rev` is your friend :)
https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt

**Comment by tgodzik** [comment]
> > It would be good to rewrite history to remove it from git blame.
> 
> `--ignore-rev` is your friend :) https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt

That's what I meant, but I forgot the exact command, thanks! Do we need to force push in that case?

**Comment by armanbilge** [comment]
Actually, it's an argument for `git blame`, not for history-rewriting. AFAIK anyway.

**Comment by tanishiking** [comment]
I personally like trailing-commas, so I am for this change :+1: (and good to see we have `.git-blame-ignore-revs`)

**Comment by kpodsiad** [comment]
There were some failures which I fixed manually, but I think `save-expect` sbt's command should do that for me(?). However, when running I got
```
[info] running (fork) tests.SaveExpect 
[info] ============
[info] = definition
[info] ============
[error] Exception in thread "main" java.util.NoSuchElementException: /Users/kpodsiadlo/opensource/metals/tests/input/src/main/scala/example/Scalalib.scala
[error]         at scala.meta.internal.mtags.SemanticdbClasspath.$anonfun$getSemanticdbPath$1(SemanticdbClasspath.scala:24)
[error]         at scala.Option.getOrElse(Option.scala:201)
[error]         at scala.meta.internal.mtags.SemanticdbClasspath.getSemanticdbPath(SemanticdbClasspath.scala:24)
[error]         at tests.DefinitionSuiteBase.$anonfun$testCases$6(DefinitionSuite.scala:64)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.meta.tokens.Tokens.foreach(Tokens.scala:29)
[error]         at tests.DefinitionSuiteBase.$anonfun$testCases$5(DefinitionSuite.scala:62)
[error]         at tests.DirectoryExpectSuite.$anonfun$saveExpect$1(DirectoryExpectSuite.scala:39)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at tests.DirectoryExpectSuite.saveExpect(DirectoryExpectSuite.scala:38)
[error]         at tests.SaveExpect$.$anonfun$main$1(SaveExpect.scala:23)
[error]         at tests.SaveExpect$.$anonfun$main$1$adapted(SaveExpect.scala:18)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at tests.SaveExpect$.main(SaveExpect.scala:18)
[error]         at tests.SaveExpect.main(SaveExpect.scala)
```

**Comment by kpodsiad** [comment]
Ok, I see what the problem is. mtags are cross compiled to `2.11.12` which doesn't support trailing comma. Is this a way to exclude scalafmt configuration for some paths?

**Comment by armanbilge** [comment]
You can do a glob override maybe?
https://github.com/typelevel/feral/blob/692d5a66046f0a8a92fa7c5ef9daf94fe3facefc/.scalafmt.conf#L4-L11

**Comment by kpodsiad** [comment]
Thanks @armanbilge! I didn't spot that we already use fileOverride in conf file 🤦

**Comment by kpodsiad** [comment]
I guess that after squash merge `.git-blame-ignore-revs` will have to be updated with valid hash of squashed commit.

**Comment by tanishiking** [comment]
> I guess that after squash merge .git-blame-ignore-revs will have to be updated with valid hash of squashed commit.

I guess we can update the `.git-blame-ignore-revs` after squash merging?

**Review by tanishiking — APPROVED** [review]
Not sure whether other maintainers like trailing commas or not, but LGTM 💯 
In terms of `.git-blame-ignore-revs`, we can update the commit hash after squash merge :)

**Comment by ckipp01** [comment]
> @tgodzik @dos65 @ckipp01 any objections?

None frome me. 👍🏼

**Comment by tgodzik** [comment]
> @tgodzik @dos65 @ckipp01 any objections?

I would still merge it after the release, but otherwise looks good!

**Comment by kpodsiad** [comment]
> I would still merge it after the release, but otherwise looks good!

Although they're just commas, I agree :D

**Comment by tgodzik** [comment]
> ouch. I can't say that I like this style change but it seems that I'm the only smiling_face_with_tear

I do agree it's not prettier, but really it's more useful on PRs

**Comment by kpodsiad** [comment]
It's really strange, sometimes I can run `save-expect`, [sometimes I can't](https://github.com/scalameta/metals/pull/4050#issuecomment-1162664600). Can someone run this and push commit with formatted input tests resources?

**Comment by tanishiking** [comment]
> It's really strange, sometimes I can run save-expect, https://github.com/scalameta/metals/pull/4050#issuecomment-1162664600. Can someone run this and push commit with formatted input tests resources?

Ok, I will

**Comment by kpodsiad** [comment]
Ok, I'm merging this bad boy.

**Pull request merged**
