### PR TITLE
Upgrade Coursier from 2.0.12 to 2.0.13 for bootstrap launcher enhancement to download artifacts using global credentials.

### PR DESCRIPTION
**Pull request by greg-a-atkinson**
An upgrade of Coursier from 2.0.12 to [2.0.13](https://github.com/coursier/coursier/releases/tag/v2.0.13) includes the enhancement:

> Launchers created by `cs bootstrap` and `cs install` are now able to read and use [credentials](https://get-coursier.io/docs/other-credentials) when fetching artifacts. (https://github.com/coursier/coursier/pull/1991)

This should resolve the  `401 Unauthorized` errors when Metals downloads artifacts from [mirror repositories](https://scalameta.org/metals/docs/troubleshooting/proxy.html) that require [authentication](https://get-coursier.io/docs/other-credentials.html#property-file):
```
Java home: C:\Users\user\working\tools\jdk1.8.0_261-x64
Metals version: 0.9.10
Error while downloading https://private.artifactory.com/artifactory/virtual-java/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-java/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar, ignoring it
Error while downloading https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar, ignoring it
Error while downloading https://private.artifactory.com/artifactory/virtual-scala/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-scala/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar, ignoring it
Error while downloading https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar, ignoring it
```

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
Thanks a lot for the pr @greg-a-atkinson! The linked work looks great. LGTM!

**Comment by greg-a-atkinson** [comment]
Thanks @ckipp01 for reviewing and merging.

**Comment by tgodzik** [comment]
We also need to upgrade coursier bootstrap inside the extension with is more important: 

https://github.com/scalameta/metals-vscode/pull/519

I can release a new version there right away if needed.

**Comment by greg-a-atkinson** [comment]
Fantastic, thank you @tgodzik.

Please feel free to raise a release at your discretion. I'm happy to wait if that will align with whatever the usual release cadence is.

**Pull request merged**
