### PR TITLE
Use git fetch --unshallow to restore version number

### PR DESCRIPTION
**Pull request by olafurpg**
On advice from https://github.com/dwijnand/sbt-dynver/issues/133#issuecomment-561585983

### CODE REVIEW

**Comment by olafurpg** [comment]
First attempt failed with
```
fatal: --unshallow on a complete repository does not make sense
```

**Comment by olafurpg** [comment]
Logs look positive

```
 [info] Set current project to default-a8016c (in build file:/home/runner/work/metals/metals/)
[info] interfaces / version
[info] 	0.7.6+395-a3d33193-SNAPSHOT
```
We can give this a try

**Comment by olafurpg** [comment]
I just realized this PR won't have any effect since the CI release happens on Travis. I pushed https://github.com/scalameta/metals/commit/2cb4e3b0916168a18df70be5458b931977fdc511 to master because we don't run PR tests on Travis.

**Comment by ckipp01** [comment]
> I just realized this PR won't have any effect since the CI release happens on Travis. I pushed 2cb4e3b to master because we don't run PR tests on Travis.

Haha, of course. We can just remove it and do the same thing for Travis I'm assuming? Is there a specific reason we cant use actions to release?

**Pull request merged**
