### PR TITLE
Implement workspace/symbol to search symbol by name.

### LINKED ISSUE #339: Implement workspace/symbol
Restart of #114 

https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_symbol

The workspace symbol request is sent from the client to the server to list project-wide symbols matching the query string.

Request:

```ts
method: 'workspace/symbol'
params: WorkspaceSymbolParams defined as follows:
/**
 * The parameters of a Workspace Symbol Request.
 */
interface WorkspaceSymbolParams {
	/**
	 * A non-empty query string
	 */
	query: string;
}
```

Requirements:

- fast, search results should come instantly as you type in the query
- should support somehow searching into library dependency symbols, maybe for queries that start with space `" "`
- fuzzy-ish search, for example query `FileStream` should match class `FileOutputStream`

### PR DESCRIPTION
**Pull request by olafurpg**
This is a large commit that implements several features

- workspace/symbol for workspace sources
- workspace/symbol for dependency classpath
- fuzzy searching for symbol queries handling things like
  - all lowercase queries
  - "smart" name-based queries like "DoSyPro" for "DocumentSymbolProvider"
  - package aware, "s.Option" matches "scala.Option"
  - inner classes aware, "M.E" matches "Map#Entry"
- low-memory indexing for fuzzy searching, the combined index should be
  <5mb even for large-ish workspaces (3k source files, 700k loc) and
  large-ish classpaths (150mb).

Fixes #339.

### CODE REVIEW

**Comment by ceedubs** [comment]
Nice! I just gave this a try and it's great.

I did notice that each result is showing up twice for me using vim-lsc. I don't know whether the issue is on the Metals or the vim-lsc side, but I thought that I would bring it up in case it's helpful.

**Comment by olafurpg** [comment]
Thanks for the feedback! Could those duplicate results be class/object companions?

**Comment by ceedubs** [comment]
That doesn't seem to be the case. For example, when I'm in [this file](https://github.com/ceedubs/irrec/blob/4228b035aea77626e9429ed17119d29939455a42/kleene/src/main/scala/KleeneF.scala) and I do a workspace search for `KleeneF` I get the following results:

```
kleene/src/main/scala/KleeneF.scala|6 col 23| "KleeneF" [Class] in ceedubs.irrec.
kleene/src/main/scala/KleeneF.scala|6 col 23| "KleeneF" [Class] in ceedubs.irrec.
kleene/src/main/scala/KleeneF.scala|8 col 8| "KleeneF" [Object] in ceedubs.irrec.
kleene/src/main/scala/KleeneF.scala|8 col 8| "KleeneF" [Object] in ceedubs.irrec.
```

So both the class and the companion object seem to show up twice.

**Comment by ceedubs** [comment]
Oh I have some additional insight on this. It appears to only duplicate the entries for files for which I have an open buffer. So maybe something is happening where it's searching the entire project and its dependencies and also separately searching any open buffers and then merging the results?

**Comment by olafurpg** [comment]
That's very helpful, thanks @ceedubs I'm able to reproduce

screenshot 2019-01-18 at 19 55 36

Something funky is going on

**Comment by olafurpg** [comment]
@ceedubs duplicate results are indeed caused by searching both workspace sources + classpath. The classpath search should only be limited to jar files, thanks for reporting!

**Comment by olafurpg** [comment]
Fix in https://github.com/scalameta/metals/pull/475

**Pull request merged**
