### PR TITLE
Add Arthur to the team!

### PR DESCRIPTION
**Pull request by tgodzik**
Arthur has done a lot of great work in Metals and Bloop (especially great job with Gradle integration) with features such as decoding semanticdb, javap or decompiling. He has also done a lot of progress with the upcoming Java support.

I am happy to welcome him to the team!

PS: @Arthurm1 feel free to merge if you feel like it! You can also add a public email if you have one.

### CODE REVIEW

**Comment by dos65** [comment]
@Arthurm1 welcome! :rocket:

**Comment by Arthurm1** [comment]
Thanks for the welcome!  Looking forward to not accidentally mucking anything up 😉

**Comment by kpodsiad** [comment]
Welcome @Arthurm1!

**Comment by ckipp01** [comment]
Welcome @Arthurm1! 🎉

**Pull request merged**
