### PR TITLE
improvement: Add benchmarks for SemanticHighlight

### PR DESCRIPTION
**Pull request by tgodzik**
They can be run using:

```
sbt bench/jmh:run -i 10 -wi 10 -f1 -t1 .*SemanticHighlightBench
```

I also reworked the CompletionBenchmark a bit since it needs a lot of the same elements.

### CODE REVIEW

**Comment by jkciesluk** [comment]
> sbt bench/jmh:run -i 10 -wi 10 -f1 -t1 .*CachedSearchAndCompilerSemanticHighlightBench

I think the command is misspelled, I get an error
```
[info] running (fork) org.openjdk.jmh.Main -i 10 -wi 10 -f1 -t1 .*CachedSearchAndCompilerSemanticHighlightBench
[error] No matching benchmarks. Miss-spelled regexp?
```

**Comment by kpodsiad** [comment]
yeah, you have to replace `CachedSearchAndCompilerSemanticHighlightBench` with the name of newly created benchmark class.

BTW, maybe it's worth to profile it and see results with flamegraph?

**Comment by tgodzik** [comment]
> > sbt bench/jmh:run -i 10 -wi 10 -f1 -t1 .*CachedSearchAndCompilerSemanticHighlightBench
> 
> I think the command is misspelled, I get an error
> 
> ```
> [info] running (fork) org.openjdk.jmh.Main -i 10 -wi 10 -f1 -t1 .*CachedSearchAndCompilerSemanticHighlightBench
> [error] No matching benchmarks. Miss-spelled regexp?
> ```

Ach, right! I changed the names just before pushing :sweat_smile:  I edited the command.

> BTW, maybe it's worth to profile it and see results with flamegraph?

We have some results [here](https://github.com/scalameta/metals/pull/4835#issuecomment-1377034654) and a good idea what of what to fix, but we can also use flamegraph if we need to optimize it further.

**Review by ckipp01 — APPROVED** [review]
Nice, I've never really dove into our benches before, so it's something I'd like to spend some more time on learning. This looks good!

**Pull request merged**
