### PR TITLE
Just to trigger CI

### PR DESCRIPTION
**Pull request by ckipp01**

### CODE REVIEW

**Comment by ckipp01** [comment]
🤔 so sending in a pr to this branch seems to not trigger the lsif job like I thought it would. Does sending in a pr to a non-default branch still trigger the default CI rather than the CI tied to that branch?

**Comment by tgodzik** [comment]
Is it correctly formatted though? `env:` seems off in the last PR. Essentially if you add a new job for pull_requests it should run in that PR unless the formatting/logic is broken.

**Comment by ckipp01** [comment]
> Is it correctly formatted though? `env:` seems off in the last PR. Essentially if you add a new job for pull_requests it should run in that PR unless the formatting/logic is broken.

Normally it will fail if the formatting in the yaml is wrong though no?

**Comment by tgodzik** [comment]
I think YAML is not an exact science :D

**Comment by ckipp01** [comment]
Ah, actually I think you're right.

**Comment by tgodzik** [comment]
Yeah, it's most likely causing the yaml file to be ignored, I also thought it might be due to it not being in main, but that was actually never the case. Which I think makes sense, since you would want to test out any changes.

**Comment by ckipp01** [comment]
Yup yup, just changed the indentation and now it's working. Freaking yaml.

**Pull request closed without merging**
