### PR TITLE
improvement: Docstring on apply method

### PR DESCRIPTION
**Pull request by jkciesluk**
Now, if docstring on apply method is empty, we try docstrings about object and case class, in that order

### CODE REVIEW

**Comment by filipwiech** [comment]
Thank you for this improvement, these kind of QoL changes really make working with Metals much nicer! :+1: 
Question (sorry if it should be obvious): does this cover "normal" (non-case) classes as well? What about Scala 3 Universal Apply? :slightly_smiling_face:

**Comment by jkciesluk** [comment]
> Question (sorry if it should be obvious): does this cover auto-generated case class apply methods and "normal" (non-case) classes as well? 

It does cover auto-generated case class apply methods, and the doc shown should will be the one describing case class. About non-case classes, it covers apply methods defined for them and constructors with `new` already worked before. It's a good idea to add tests covering these cases too. 

> What about Scala 3 Universal Apply?

Thats' a good catch, I forgot about this case at first, but according to https://docs.scala-lang.org/scala3/reference/other-new-features/creator-applications.html, `apply` method is generated together with companion object, if class doesn’t have one yet, so this should work the same way as for case classes. I will add tests to make sure.

**Comment by filipwiech** [comment]
Awesome, sounds great! :+1: And thanks for additional tests, much appreciated. :slightly_smiling_face:

**Review by tgodzik — APPROVED** [review]
LGTM!

**Pull request merged**
