### PR TITLE
Add backticks where needed in "convert to named arguments"

### LINKED ISSUE #4301: Convert to named arguments doesn't handle backticked names
### Describe the bug

Executing code action on
```scala
//> using scala "2.13.8"

object Main {
  final case class Foo(`type`: Int, `def`: String)

  val x = Foo(
    1,@@
    "John Wick"
  )
}
```
will yield

```scala
//> using scala "2.13.8"

object Main {
  final case class Foo(`type`: Int, `def`: String)

  val x = Foo(
    type = 1,
    def = "John Wick"
  )
}
```

### Expected behavior

names are bacticked if necessary
```scala
//> using scala "2.13.8"

object Main {
  final case class Foo(`type`: Int, `def`: String)

  val x = Foo(
    `type` = 1,
    `def` = "John Wick"
  )
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8+38-1832a3cf-SNAPSHOT

### Extra context or search terms

_No response_

### PR DESCRIPTION
**Pull request by kubukoz**
Fixes #4301.

### CODE REVIEW

**Comment by kubukoz** [comment]
I'll check the failure later but can't make this a draft from my phone 😅

**Review by dos65 — COMMENTED** [review]
@kubukoz Thx for contribution!

LGTM! The only you need is to run scalafix for mtags

**Comment by kubukoz** [comment]
scalafix done!

**Review by dos65 — APPROVED** [review]

**Review by tgodzik — APPROVED** [review]
Thanks! :tada:

**Pull request merged**
