### PR TITLE
bump: bloop

### PR DESCRIPTION
**Pull request by kpodsiad**

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
👍🏼 Is there something specific this one brings in?

**Comment by kpodsiad** [comment]
@ckipp01 Thanks for the quick response. This version contains only one minor thing which is super useful for Test Explorer.

**Comment by kpodsiad** [comment]
> This version contains only one minor thing which is super useful for Test Explorer.

It's literally one-word change so I'll merge this without waiting for the CI.

**Comment by tanishiking** [comment]
👍 This bump introduces this one? https://github.com/scalacenter/bloop/pull/1703

**Pull request merged**
