### PR TITLE
fix: do not decode every URI when invoking `toAbsolutePath`

### PR DESCRIPTION
**Pull request by kpodsiad**
Yesterday on discord it was reported that an internal server error happens when Metals have to deal with a directory that contains spaces. The source of the problem was fact that Mtags and Metals xtension method for string differentiated in implementation.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM!

**Comment by tgodzik** [comment]
Actually, could you run scalafix before merging?

**Comment by kpodsiad** [comment]
Oh, I didn't see Scalafix fail

**Comment by Arthurm1** [comment]
LGTM

**Review by Arthurm1 — APPROVED** [review]

**Comment by ckipp01** [comment]
😆 merged because I literally just hit on this at work and I need this fix.

**Pull request merged**
