### PR TITLE
Move slow tests to separate directories and run them separately on Travis

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/metals/issues/754

### CODE REVIEW

**Comment by tgodzik** [comment]
> Ran for 18 min 15 sec

@olafurpg I separated each build tool slow suite and it runs quicker now. Is this what you meant?

**Comment by olafurpg** [comment]
> I separated each build tool slow suite and it runs quicker now. Is this what you meant?


Nice! That speedup looks great 😍

**Comment by tgodzik** [comment]
It takes a maximum of 14 minutes, but I guess it also depends on how many workers we have. Still I think it's a nice speedup.

**Comment by olafurpg** [comment]
Travis allows a maximum number of parallel jobs across GitHub organizations and I recently merged a few PRs in scalameta/metabrowse

**Comment by tgodzik** [comment]
> Travis allows a maximum number of parallel jobs across GitHub organizations and I recently merged a few PRs in scalameta/metabrowse

I figured as much, still it will be faster. As fast as we can get it.

**Pull request merged**
