### PR TITLE
Generate missing memebers quick fix

### PR DESCRIPTION
**Pull request by dos65**
How it works:
file

### CODE REVIEW

**Comment by gabro** [comment]
Hi @dos65, thanks a lot for the contribution!

Have you checked https://github.com/scalameta/metals-feature-requests/issues/59? It has already a WIP PR here #1379

Maybe you can compare notes and see whether there are significant differences between your work and @tanishiking’s?

For the future I would recommend checking the existing feature requests/PR and/or pinging one of the maintainers on gitter or discord before working on a feature. We should be able to evaluate the complexity beforehand and avoid duplicate work :-)

Thanks again!

**Comment by dos65** [comment]
Ough! @tanishiking made it faster than me. At the begging of the work I didn't see that request.
Yes - I'll check if there any differences

**Comment by dos65** [comment]
I've checked #1379. @tanishiking's PR is even better than mine because it covers implementation for anonymous classes.

I close this one. Next time I will definitely contact maintainers before starting work!

**Comment by gabro** [comment]
🙏 thanks and looking forward for your next contributions!

**Comment by tanishiking** [comment]
Sorry for the duplication:pray: I'm also looking forward to your next contributions!

**Pull request closed without merging**
