### PR TITLE
improvement: Send error back to client to show

### PR DESCRIPTION
**Pull request by tgodzik**
Previously, it would be very difficult to show a proper error message to the user. Especially in VS Code a generic message was show, which was very confusing for users.

Now, we send the error message in the response so that the client can handle it as they want.

I wonder if we should keep displaying the message, but not sure if it's not better to just change the clients here to show the error.

Related to https://github.com/scalameta/metals-vscode/pull/1438

### CODE REVIEW

**Comment by tgodzik** [comment]
@ckipp01 what do you think, should we keep displaying the error message? via the standard showMessage mechanism?

**Comment by ckipp01** [comment]
> I wonder if we should keep displaying the message, but not sure if it's not better to just change the clients here to show the error.

Yea I think maybe this might be best? I think each of the clients that are doing any DAP related stuff will have an extension that can probably handle this in an appropriate way for that client.

**Comment by filipwiech** [comment]
My 2 cents: could we still retain the message sent through the standard LSP? The reason I ask is that the more special things like that are used, the more they require support and maintenance in all the clients. Scala is not as popular as some other languages (think for example Python, Rust, Go) and as a result it often doesn't get first-class support out of the box. The community has limited manpower to add and update special handling. While VSCode and Neovim do get great support from you (big thanks to everyone involved and for @ckipp01 for his awesome Neovim plugin) there are other editors which do not (like Helix, Emacs). I believe the more common protocol is used the better it is for the overall user experience. Sorry for the long message. :slightly_smiling_face:

**Comment by tgodzik** [comment]
@filipwiech thinking it over I realized we can rely on lsp4j's own exception, which will be sent properly to the client (so using normal LSP mechanisms). Did another PR since it's totally different https://github.com/scalameta/metals/pull/5864

It might need to fixes to tests, but looks to be working pretty well.

**Pull request closed without merging**
