### PR TITLE
Make sure higher kinded functions in signatures are inferred properly

### PR DESCRIPTION
**Pull request by tgodzik**
Previously for a higher kinded type like:

```scala
TypeRef(
  pre = <noprefix>,
  sym = class Resource,
  args = List(
    PolyType(
      typeParams = List(type x),
      resultType = TypeRef(
        pre = <noprefix>,
        sym = type F,
        args = List(TypeRef(pre = <noprefix>, sym = type x, args = List()))
      )
    ),
    TypeRef(pre = <noprefix>, sym = class Unit, args = List())
  )
)
```

we would print:

```scala
Resource[[x]F[x],Unit]
```

Which is nothing that can actually work in the code. Instead, it should just be `Resource[F, Unit]` as the type constructors can't really appear in signatures (I think)

Fixes https://github.com/scalameta/metals/issues/2558

I am not 100% sure of this solution, but I this seems to work now. I anyone has a better idea about `PolyType` or higher kinded types do let me know. As it stands, this should not break anything, but can fix things.

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
Honestly I'm not really sure if there is a better way to do this or if this misses something etc, but this looks good to me from what I can tell 👍🏼 LGTM!

**Review by dos65 — APPROVED** [review]
LGTM :+1:

**Review by tanishiking — APPROVED** [review]
LGTM! :tada:

**Comment by kubukoz** [comment]
🥰

**Pull request merged**
