### PR TITLE
Integrate with bsp language server

### PR DESCRIPTION
**Pull request by jvican**
This is a very work in progress that implements BSP integration. For more information on the protocol, visit https://github.com/scalacenter/bsp.

### CODE REVIEW

**Comment by gabro** [comment]
404 on bsp, is it private?

**Comment by jvican** [comment]
Yup, we need to wait a little bit longer :smile:

**Comment by olafurpg** [comment]
We just merged the sbt server integration in #170, can you please rebase on top of master?

**Comment by olafurpg** [comment]
Closing to clear the PR queue. I am excited to use BSP to make it easier to import projects!

**Pull request closed without merging**
