### PR TITLE
Update sbt to 1.4.0

### PR DESCRIPTION
**Pull request by ckipp01**
This also syncs to the lastest sbt-extras

### CODE REVIEW

**Comment by ckipp01** [comment]
:/ Totally forgot about this: https://github.com/scalameta/munit/issues/210

Looks like we are hitting on the same thing.

**Comment by tgodzik** [comment]
> :/ Totally forgot about this: [scalameta/munit#210](https://github.com/scalameta/munit/issues/210)
> 
> Looks like we are hitting on the same thing.

Yeah, we might need to hold off on the update for a bit unless we are able to fix it inside sbt build definition.

**Comment by ckipp01** [comment]
> Yeah, we might need to hold off on the update for a bit unless we are able to fix it inside sbt build definition.

I'm looking around at the various discussions, but has it been pinned down what is actually causing this? If I remember correctly it was something with dotty docs? Is there an issue logged for it?

**Comment by ckipp01** [comment]
I'm going to close this for now then.

**Comment by tgodzik** [comment]
I think that will be fix in the next version of Scala 3 from what I see. Maybe 0.27.0 and 0.28.0-RC1.

**Comment by kpbochenek** [comment]
We will be able to upgrade only when we completely drop 0.27.0-RC1? 
Do I correctly understand that mtags with dotty <= 0.27.0-RC1 cannot use sbt 1.4.0?

**Comment by tgodzik** [comment]
> We will be able to upgrade only when we completely drop 0.27.0-RC1?
> Do I correctly understand that mtags with dotty <= 0.27.0-RC1 are not compatible with sbt 1.4.0?

I think so unless we fix it in build.sbt we will need to wait.

**Pull request closed without merging**
