### PR TITLE
Auto approve PR by scalameta-bot

### PR DESCRIPTION
**Pull request by tanishiking**
part of https://github.com/scalameta/metals/issues/4333

- Auto-approve the PRs that is created by `scalameta-bot` and has label `semver-spec-patch`.
- `scalameta-bot` will approve the PR

Added this auto-approve workflow because scalameta/metals
requires PRs to receive at least one approval from authorized users
(maintainers) to merge.
Therefore, until someone approve the PR, mergify cannot merge the PR.

This workflow will self-approve (by `scalameta-bot`) and enable mergify
to auto-merge the library update PRs.

---

- I didn't use mergify's auto-review functionality, because mergify
  cannot specify a user who approve the PR (with a free OSS plan)
  - https://docs.mergify.com/actions/review/
- This action doesn't depends on other workflows result, which means will auto-approve even if the CIs fail.
  - It's ideal approve only when CIs passed, but depending on other workflows' status in github actions are bit complicated (in comparison to mergify), let mergify check the CI statuses.
  - see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
- concerns
  - Can scalameta-bot self-approve?
  - Does scalameta-bot's approval unlock merging? (maybe we have to give
    scalameta-bot write right to this repo?)

### CODE REVIEW

**Comment by tanishiking** [comment]
I wish I could test the workflow without merging this to `base` branch, but `gh workflow run -- ref ...` doesn't work for the `workflow_dispatch` until it ran at least once. https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo#comment120369049_67840292

**Comment by dos65** [comment]
@tanishiking I'm wondering maybe we can allow mergify user to merge PR without an approval?

**Comment by tanishiking** [comment]
> I'm wondering maybe we can allow mergify user to merge PR without an approval?

Yeah, if we can the procedure will be much simpler, but I'm not sure if is possible.

- mergify honors the branch protection settings
  - if the repository requires PR to receive at least one approval or pass specific tests, mergify won't merge the PR until the conditions are met (even if the mergify bot can ignore them)
- To let mergify ignore the branch protection, the mergify bot has to be an admin role (repository owner?), but I'm not sure it is safe to give that strong right to the bot.

**Comment by tgodzik** [comment]
> Can scalameta-bot self-approve?

I think users cannot self approve, so that might not work :thinking: We would need another bot for that.

**Comment by tgodzik** [comment]
> > Can scalameta-bot self-approve?
> 
> I think users cannot self approve, so that might not work thinking We would need another bot for that.

Or move back to original scala-steward, which would mean scalameta bot could approve

**Comment by tgodzik** [comment]
Ok, I added scalameta-bot to the list that should be able to merge without approvals, let me know if that works!

**Comment by tgodzik** [comment]
och wait, it's the mergify user :thinking:  That should work then :sweat_smile:

**Comment by tgodzik** [comment]
> Ok, I added scalameta-bot to the list that should be able to merge without approvals, let me know if that works!

och no, that will not work since mergify is the one merging :thinking:  Can we switch the user that does the merging?

**Comment by tanishiking** [comment]
Thanks, @tgodzik !
Unfortunately, mergify cannot switch the bot user with a free (OSS) plan, maybe we should use GitHub action https://github.com/pascalgn/automerge-action instead. Let me try that action with scalameta-bot :)

**Comment by tanishiking** [comment]
I did some experiments

## Tried automerge-action
Try [automerge-action](https://github.com/pascalgn/automerge-action) to merge PRs by an account that can bypass branch protections

Failed, GitHub API doesn't allow us to bypass branch protection via API (so, we can't bypass via GitHub action, and mergify).
https://github.com/community/community/discussions/9829

We get logs like ...

```
2022-09-06T14:10:47.701Z INFO  Current PR status: mergeable_state: blocked
2022-09-06T14:10:47.702Z INFO  PR not ready to be merged after 6 tries
2022-09-06T14:10:47.703Z INFO  Action result: { mergeResult: 'not_ready', pullRequestNumber: 63 }
```

for full logs https://github.com/tanishiking/semanticdb-for-scala3/runs/8208819598?check_suite_focus=true

So, **we (even admin users) can't auto-merge PRs without approving the PRs (under the branch protection)**

## who can approve PR?

I confirmed PR approval by `github-action` (bot) unlock merging for branch protection https://github.com/tanishiking/semanticdb-for-scala3/pull/63 :tada:

I haven't tested self-approve (I get 404 if I use a custom GitHub-token for [auto-approve-action](https://github.com/hmarr/auto-approve-action) 🤔 )

## Conclusion

So the whole process looks like

- `github-action` bot auto-approve PRs created by `scalameta-bot` with `semver-spec-patch` using [auto-approve-action](https://github.com/hmarr/auto-approve-action)
- mergify will merge the PR if CIs passed

**Comment by tanishiking** [comment]
I'll update the PR tomorrow.

**Comment by tanishiking** [comment]
Hey I updated the change to approve PRs by github-actions (bot) which should unlock the branch protection

**Comment by tgodzik** [comment]
> Hey I updated the change to approve PRs by github-actions (bot) which should unlock the branch protection

But will scalameta-bot be able to approve it's own PR?

**Comment by tanishiking** [comment]
> scalameta-bot be able to approve it's own PR?

Haven't tested, but I don't think so. But I confirmed github-action (bot) does unlock branch protection

> I confirmed PR approval by github-action (bot) unlock merging for branch protection https://github.com/tanishiking/semanticdb-for-scala3/pull/63 🎉
> I haven't tested self-approve (I get 404 if I use a custom GitHub-token for [auto-approve-action](https://github.com/hmarr/auto-approve-action) 🤔 )

**Review by tgodzik — APPROVED** [review]
Ach! So that will be the the github bot, makes sense! Great work!

**Comment by tanishiking** [comment]
Thanks! let's see how it goes

**Pull request merged**
