### PR TITLE
Upgrade to Bloop v1.3.5.

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by olafurpg** [comment]
Test failures seem to be related to the SemanticDB compiler plugin 
```
[error] Failed tests:
[error] 	tests.DocumentHighlightLspSuite
[error] 	tests.DefinitionLspSuite
[error] 	tests.FileWatcherLspSuite
[error] 	tests.ImplementationSuite
[error] 	tests.ReferenceLspSuite
[error] 	tests.CodeLensesLspSuite
[error] 	tests.QuickBuildSuite
[error] 	tests.WorkspaceSymbolLspSuite
```

@tgodzik could you maybe try to investigate?

**Comment by tgodzik** [comment]
> Test failures seem to be related to the SemanticDB compiler plugin
> 
> ```
> [error] Failed tests:
> [error] 	tests.DocumentHighlightLspSuite
> [error] 	tests.DefinitionLspSuite
> [error] 	tests.FileWatcherLspSuite
> [error] 	tests.ImplementationSuite
> [error] 	tests.ReferenceLspSuite
> [error] 	tests.CodeLensesLspSuite
> [error] 	tests.QuickBuildSuite
> [error] 	tests.WorkspaceSymbolLspSuite
> ```
> 
> @tgodzik could you maybe try to investigate?

Quickly checked local snapshot and seems to work :/ Will investigate more after my flight lands

**Comment by tgodzik** [comment]
Is it possible that the source root is now badly configured? We override it in bloop now.

**Comment by tgodzik** [comment]
Seems we specified the workspace directory badly, which pointed to the project directory.

**Comment by jvican** [comment]
Can we remove the bloop script you use as well?

**Comment by olafurpg** [comment]
@jvican can you elaborate? The tests are passing now, the bug was on the Metals side.

Travis is failing with a familiar error

```
 There is insufficient memory for the Java Runtime Environment to continue.

# Native memory allocation (mmap) failed to map 133693440 bytes for committing reserved memory.

# An error report file with more information is saved as:

# /home/travis/build/scalameta/metals/tests/slow/hs_err_pid6157.log
```
We may want to consider moving those tests to GitHub Actions 🤔

**Comment by tgodzik** [comment]
> @jvican can you elaborate? The tests are passing now, the bug was on the Metals side.
> 
> Travis is failing with a familiar error
> 
> ```
>  There is insufficient memory for the Java Runtime Environment to continue.
> 
> # Native memory allocation (mmap) failed to map 133693440 bytes for committing reserved memory.
> 
> # An error report file with more information is saved as:
> 
> # /home/travis/build/scalameta/metals/tests/slow/hs_err_pid6157.log
> ```
> 
> We may want to consider moving those tests to GitHub Actions

@jvican is talking about the script we are using to run bloop in the background. I can fix that in a separate PR. Let's merge this one and I can start working on the release tomorrow.

**Comment by tgodzik** [comment]
Maven failure unrelated - it will be available tomorrow most likely. Will check before running release. I will experiment with adding more github actions in a separate PR since they seem to be working alright now.

**Pull request merged**
