### PR TITLE
Skip scripted tests if there is no diff in sbt-metals

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by olafurpg** [comment]
I tested manually for a positive check and it seems to work as expected.

**Comment by olafurpg** [comment]
Keep an eye for the CI when doing the next change on sbt-metals!

**Comment by laughedelic** [comment]
See also https://github.com/facebook/react/pull/2000/files, could be useful to exclude docs-only changes from running _any_ tests.

**Comment by olafurpg** [comment]
That's cool. Build tools like pants/bazel make doing these tricks both easy and more robust.

**Pull request merged**
